version: '3'
  
services: 
  homeseer:
    image: "berryk/homeseer:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "11000:11000" 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
