# To run:
# docker run -d --restart unless-stopped --net=host --name MusicCastControl-container MusicCastControl

FROM node:latest
MAINTAINER Keith Berry "keithwberry@gmail.com"

RUN npm install -g mqtt-scripts