version: '3'
  
services: 
  wetty:
    image: "berryk/wetty:latest"
    restart: unless-stopped
    ports:
      - "32768:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
