version: "3"

services:
  nginx:
    build: nginx/.
    #restart: "unless-stopped"
    ports:
      - 443:443

  auth-duo:
    build: duo-auth-request/.
    #restart: "unless-stopped"
    ports: 
      - 3000:3000
