version: "3.2"

services:

   cloudflare:
    container_name: cloudflare
    hostname: cloudflare 
    build: ../cloudflare/. 
    restart: always
    #    ports: 
    #  - "443:443" 
    networks:
      - cloudflare 
    volumes: 
      - ~/secrets/cloudflare:/etc/cloudflared:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   portainer:
    container_name: portainer
    hostname: portainer
    image: "portainer/portainer:latest"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   nginx:
    container_name: nginx
    hostname: nginx
    build: ../nginx/nginx/.
    restart: always
    #ports:
    # - 443:443 
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
    networks:
      - cloudflare 
    #labels:
    #     hera.hostname: nginx.88highlandavenue.com
    #  hera.port: 443 
    logging:
     driver: "json-file"
     options:
      max-size: "10m"
      max-file: "3"
   
   dd-agent:
    container_name: dd-agent
    hostname: ddagent
    image: datadog/agent:latest
    restart: always
    environment:
      - DD_API_KEY=7aa7e30d732f2e062e9ed52b3d3102bf
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_ENABLED=true
      - DD_AC_EXCLUDE="name:dd-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
#     - /opt/datadog-agent/conf.d:/conf.d:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   dropbox:
    image: drodgers/dropbox
    container_name: dropbox
    hostname: dropbox
    restart: always
    ports:
      - "17500:17500"
    volumes:
      -  type: volume
         source: dropbox
         target: /dbox/Dropbox
      -  type: volume
         source: dropbox-r
         target: /dbox/Dropbox/R
      -  type: volume
         source: docker-registry
         target: /dbox/Dropbox/docker-registry
      -  type: volume
         source: dropbox-homeseer
         target: /dbox/Dropbox/homeseer
      -  type: volume
         source: dropbox-config
         target: /dbox/.dropbox
      -  type: volume
         source: pihole 
         target: /dbox/Dropbox/pihole
      -  type: volume
         source: dnsmasq
         target: /dbox/Dropbox/dnsmasq
      - ~/dropbox:/dbox/Dropbox/linux-dropbox
      - ~/secrets:/dbox/Dropbox/secrets
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   rstudio:
 #    image: berryk/rstudio
 #   image: rocker/rstudio
    build: ../rstudio/.
    container_name: rstudio
    hostname: rstudio
    restart: always
    ports:
      - 8787:8787
    environment:
      - ROOT="TRUE"
#      - PASSWORD=admin
      - DISABLE_AUTH=true
    volumes:
      - type: volume
        source: dropbox-r
        target: /home/rstudio/dropbox
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.ssh:/home/rstudio/.ssh:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   vscode:
    image: theiaide/theia-full:next
    container_name: vscode
    hostname: vscode
    restart: always
    ports:
      - 4000:3000
    volumes:
      - ~/dropbox:/home/theia/dropbox
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.ssh:/home/theia/.ssh
    user: "1000:1000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    hostname: jupyter
    restart: always
    command: start.sh jupyter lab --LabApp.token=''
    ports:
      - 8888:8888
    volumes:
      - ~/dropbox:/home/jovyan/dropbox
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.ssh:/home/jovyan/.ssh
    user: "1000:1000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   homeseer:
#    image: "marthoc/homeseer"
    build: ../homeseer/.
    container_name: homeseer
    hostname: homeseer
    restart: always
    #network_mode: "host"
    ports:
      - "8880:80"
      - "11000:11000"
    volumes:
      - type: volume
        source: dropbox-homeseer
        target: /HomeSeer
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   remotespark:
    container_name: remotespark
    hostname: remotespark
    image: "berryk/remotespark"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   mqtt:
    container_name: mqtt
    hostname: mqtt
    image: "toke/mosquitto"
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   chromecast-mqtt:
    container_name: chromecast-mqtt
    hostname: chromecast-mqtt
    image: "berryk/chromecast-mqtt"
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   musiccastcontrol:
    container_name: musiccastcontrol
    hostname: musiccastcontrol
#    image: "berryk/musiccastcontrol"
    build: ../MusicCastControl/.
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   mqtt-scripts:
    container_name: mqtt-scripts
    hostname: mqtt-scripts
    #image: "berryk/mqtt-scripts-scripts"
    build: ../mqtt-scripts-scripts/.
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   wetty:
    container_name: wetty
    hostname: wetty
#    image: "krishnasrinivas/wetty"
    image: "berryk/wetty"
    restart: always
    ports:
      - "32768:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   xrdp-stretch:
    container_name: xrdp-stretch
    hostname: xrdp-stretch
    #image: "berryk/mqtt-scripts-scripts"
    build: ../xrdp-stretch/.
    #user: dockerx
    restart: always
    #network_mode: "host"
    ports:
      - "4350:4350"
      - "4389:4389"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

   pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    volumes: 
      - type: volume
        source: pihole
        target: /etc/pihole/
      - type: volume
        source: dnsmasq
        target: /etc/dnsmasq.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment: 
      WEBPASSWORD:
      ServerIP: 192.168.1.200 
      TZ: America/New_York  
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dropbox:
  dropbox-r:
  docker-registry:
  dropbox-homeseer:
  dropbox-config:
  pihole:
  dnsmasq:

networks:
  cloudflare:
